address_book/src/AppBundle/Entity/Contact.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Contact
 *
 * @ORM\Table(name="contact")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ContactRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Contact
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="surname", type="string", length=255, nullable=true)
     */
    private $surname;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Address", mappedBy="contact")
     */
    private $addresses;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\PhoneNumber", mappedBy="contact")
     */
    private $phoneNumbers;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\EmailAddress", mappedBy="contact")
     */
    private $emailAddresses;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\ContactGroup", mappedBy="contacts")
     */
    private $contactGroups;

    /**
     * @var string
     *
     * @ORM\Column(name="picture_path", type="string", length=255)
     */
    private $picturePath;

    /**
     * @var UploadedFile
     *
     * @Assert\File(maxSize="1M")
     * @Assert\File(mimeTypes={ "image/jpeg", "image/png" })
     */
    private $pictureFile;

    /**
     * Contact constructor.
     */
    public function __construct()
    {
        $this->addresses = new ArrayCollection();
        $this->phoneNumbers = new ArrayCollection();
        $this->emailAddresses = new ArrayCollection();
        $this->contactGroups = new ArrayCollection();
        // default picture for new contacts
        $this->picturePath = 'noPicture.png';
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Contact
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set surname
     *
     * @param string $surname
     * @return Contact
     */
    public function setSurname($surname)
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * Get surname
     *
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Contact
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add addresse
     *
     * @param Address $address
     * @return Contact
     */
    public function addAddress(Address $address)
    {
        $this->addresses[] = $address;

        return $this;
    }

    /**
     * Remove address
     *
     * @param Address $address
     */
    public function removeAddress(Address $address)
    {
        $this->addresses->removeElement($address);
    }

    /**
     * Get addresses
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Add phoneNumber
     *
     * @param PhoneNumber $phoneNumber
     * @return Contact
     */
    public function addPhoneNumber(PhoneNumber $phoneNumber)
    {
        $this->phoneNumbers[] = $phoneNumber;

        return $this;
    }

    /**
     * Remove phoneNumber
     *
     * @param PhoneNumber $phoneNumber
     */
    public function removePhoneNumber(PhoneNumber $phoneNumber)
    {
        $this->phoneNumbers->removeElement($phoneNumber);
    }

    /**
     * Get phoneNumbers
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPhoneNumbers()
    {
        return $this->phoneNumbers;
    }

    /**
     * Add emailAddress
     *
     * @param EmailAddress $emailAddress
     * @return Contact
     */
    public function addEmailAddress(EmailAddress $emailAddress)
    {
        $this->emailAddresses[] = $emailAddress;

        return $this;
    }

    /**
     * Remove emailAddress
     *
     * @param EmailAddress $emailAddress
     */
    public function removeEmailAddress(EmailAddress $emailAddress)
    {
        $this->emailAddresses->removeElement($emailAddress);
    }

    /**
     * Get emailAddresses
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEmailAddresses()
    {
        return $this->emailAddresses;
    }

    /**
     * Add contactGroup
     *
     * @param ContactGroup $contactGroup
     * @return Contact
     */
    public function addContactGroup(ContactGroup $contactGroup)
    {
        $this->contactGroups[] = $contactGroup;

        return $this;
    }

    /**
     * Remove contactGroup
     *
     * @param ContactGroup $contactGroup
     */
    public function removeContactGroup(ContactGroup $contactGroup)
    {
        $this->contactGroups->removeElement($contactGroup);
    }

    /**
     * Get contactGroups
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getContactGroups()
    {
        return $this->contactGroups;
    }

    /**
     * Get picture path
     *
     * @return string
     */
    public function getPicturePath()
    {
        return $this->picturePath;
    }

    /**
     * Set picture path
     *
     * @param $picturePath
     * @return $this
     */
    public function setPicturePath($picturePath)
    {
        $this->picturePath = $picturePath;

        return $this;
    }

    /**
     * Get uploaded picture file
     *
     * @return UploadedFile
     */
    public function getPictureFile()
    {
        return $this->pictureFile;
    }

    /**
     * Set uploaded picture file
     *
     * @param UploadedFile $pictureFile
     * @return $this
     */
    public function setPictureFile($pictureFile)
    {
        $this->pictureFile = $pictureFile;

        return $this;
    }

    public function getAbsolutePicturePath()
    {
        return null === $this->picturePath ? null : $this->getUploadRootDir() . '/' . $this->picturePath;
    }

    public function getWebPicturePath()
    {
        return null === $this->picturePath ? null : $this->getUploadDir() . '/' . $this->picturePath;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded documents should be saved
        return __DIR__ . '/../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw when displaying uploaded doc/image in the view.
        return 'uploads/pictures';
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->pictureFile) {
            // unikalna nazwa
            $this->setPicturePath(uniqid() . '.' . $this->pictureFile->guessExtension());
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->pictureFile) {
            return;
        }

        $this->pictureFile->move($this->getUploadRootDir(), $this->picturePath);

        unset($this->pictureFile);
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($file = $this->getAbsolutePicturePath()) {
            unlink($file);
        }
    }
}

address_book/src/AppBundle/Form/ContactType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('surname')
            ->add('description')
            ->add('pictureFile', FileType::class, [
                'label' => 'Contact picture (jpg or png image)',
                'required' => false
            ]);
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Contact'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_contact';
    }


}

address_book/src/AppBundle/Controller/ContactController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Contact;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/contact")
 */
class ContactController extends Controller
{
    /**
     * @Route("/new")
     * @Template("AppBundle:Contact:new.html.twig")
     * @param Request $request
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function newAction(Request $request)
    {
        $contact = new Contact();

        $form = $this->createForm('AppBundle\Form\ContactType', $contact);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this
                ->getDoctrine()
                ->getManager();

            $em->persist($contact);
            $em->flush();

            return $this->redirectToRoute('app_contact_show', ['id' => $contact->getId()]);
        }

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route("/{id}/modify")
     * @Template("AppBundle:Contact:modify.html.twig")
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function modifyAction(Request $request, $id)
    {
        $contact = $this
            ->getDoctrine()
            ->getRepository('AppBundle:Contact')->find($id);

        $form = $this->createForm('AppBundle\Form\ContactType', $contact);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this
                ->getDoctrine()
                ->getManager();

            $em->flush();

            return $this->redirectToRoute('app_contact_showall');
        }

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @Route("/{id}/delete")
     * @Method("DELETE")
     */
    public function deleteAction($id)
    {
        $contact = $this
            ->getDoctrine()
            ->getRepository('AppBundle:Contact')->find($id);

        if (!$contact) {
            throw $this->createNotFoundException('Contact not found');
        }

        $em = $this
            ->getDoctrine()
            ->getManager();

        $em->remove($contact);
        $em->flush();

        return $this->redirectToRoute('app_contact_showall');
    }

    /**
     * @Route("/{id}")
     * @Template("AppBundle:Contact:show.html.twig")
     * @return array
     */
    public function showAction($id)
    {
        $contact = $this
            ->getDoctrine()
            ->getRepository('AppBundle:Contact')->find($id);

        if (!$contact) {
            throw $this->createNotFoundException('No contact found');
        }

        // for adding contact to group
        /** @ToDo: Get only the groups, that contact not belong to */
        $contactGroups = $this
            ->getDoctrine()
            ->getRepository('AppBundle:ContactGroup')->findAll();

        return [
            'contact' => $contact,
            'contactGroups' => $contactGroups
        ];
    }

    /**
     * @Route("/")
     * @Template("AppBundle:Contact:showAll.html.twig")
     * @return array
     */
    public function showAllAction()
    {
        $contacts = $this
            ->getDoctrine()
            ->getRepository('AppBundle:Contact')->findAll();

        return [
            'contacts' => $contacts
        ];
    }

    /**
     * @Route("/contactGroup/add")
     * @Method("POST")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @internal param integer $contactId
     * @internal param integer $contactGroupId
     */
    public function addToGroup(Request $request)
    {
        $contactId = $request->request->get('contactId');
        $contactGroupId = $request->request->get('contactGroupId');

        $contact = $this
            ->getDoctrine()
            ->getRepository('AppBundle:Contact')->find($contactId);

        if (!$contact) {
            throw $this->createNotFoundException('Contact not found');
        }

        $contactGroup = $this
            ->getDoctrine()
            ->getRepository('AppBundle:ContactGroup')->find($contactGroupId);

        if (!$contactGroup) {
            throw $this->createNotFoundException('Contact group not found');
        }

        $contact->addContactGroup($contactGroup);
        $contactGroup->addContact($contact);

        $em = $this
            ->getDoctrine()
            ->getManager();

        $em->flush();

        return $this->redirectToRoute('app_contact_show', ['id' => $contactId]);
    }

    /**
     * @Route("/contactGroup/remove")
     * @Method("POST")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function removeFromGroup(Request $request)
    {
        $contactId = $request->request->get('contactId');
        $contactGroupId = $request->request->get('contactGroupId');

        $contact = $this
            ->getDoctrine()
            ->getRepository('AppBundle:Contact')->find($contactId);

        if (!$contact) {
            throw $this->createNotFoundException('Contact not found');
        }

        $contactGroup = $this
            ->getDoctrine()
            ->getRepository('AppBundle:ContactGroup')->find($contactGroupId);

        if (!$contactGroup) {
            throw $this->createNotFoundException('Contact group not found');
        }

        $contact->removeContactGroup($contactGroup);
        $contactGroup->removeContact($contact);

        $em = $this
            ->getDoctrine()
            ->getManager();

        $em->flush();

        return $this->redirectToRoute('app_contact_show', ['id' => $contactId]);
    }
}

address_book/src/AppBundle/Resources/views/Contact/show.html.twig
{% extends '::base.html.twig' %}

{% block body %}

    <p><a href="{{ path('app_contact_showall') }}">Show all contacts</a></p>

    <img src="{{ asset(contact.webPicturePath)|default(asset('uploads/pictures/noPicture.png')) }}" width="100px" height="100px">
    <p>{{ contact.name }} {{ contact.surname }}</p>
    <p>{{ contact.description }}</p>

    <h5>Contact groups:</h5>
    <ul>
        {% for group in contact.contactGroups %}
            <li>
                {{ group.name }} |
                <form action="{{ path('app_contact_removefromgroup') }}" method="POST">
                    <input name="contactId" type="hidden" value="{{ contact.id }}">
                    <input name="contactGroupId" type="hidden" value="{{ group.id }}">
                    <input type="submit" value="Remove from group">
                </form>
            </li>
        {% else %}
            <p>No group found</p>
        {% endfor %}
    </ul>

    <p>Add contact to group:</p>
    <form action="{{ path('app_contact_addtogroup') }}" method="POST">
        <input name="contactId" type="hidden" value="{{ contact.id }}">
        <select name="contactGroupId">
            {% for group in contactGroups %}
                <option value="{{ group.id }}">{{ group.name }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Add to group">
    </form>

    <hr>

    <h3>Addresses</h3>
    <ul>
        {% for address in contact.addresses %}
            <li>
                {{ address.type }} | {{ address.city }}, {{ address.streetName }} {{ address.streetNumber }}
                |
                <form action="{{ path('app_address_delete', {'contactId': contact.id, 'addressId': address.id}) }}"
                      method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    <input type="submit" value="Delete">
                </form>
                |
                <a href="{{ path('app_address_modify', {'contactId': contact.id, 'addressId': address.id}) }}">modify</a>
            </li>
        {% else %}
            <p>No addresses found :(</p>
        {% endfor %}
    </ul>

    <a href="{{ path('app_address_new', {'contactId': contact.id}) }}">Add address</a>

    <hr>

    <h3>Phone numbers</h3>
    <ul>
        {% for phoneNumber in contact.phoneNumbers %}
            <li>
                {{ phoneNumber.type }} | {{ phoneNumber.number }}
                |
                <form action="{{ path('app_phonenumber_delete', {'contactId': contact.id, 'phoneNumberId': phoneNumber.id}) }}"
                      method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    <input type="submit" value="Delete">
                </form>
                |
                <a href="{{ path('app_phonenumber_modify', {'contactId': contact.id, 'phoneNumberId': phoneNumber.id}) }}">modify</a>
            </li>
        {% else %}
            <p>No phone numbers found :(</p>
        {% endfor %}
    </ul>

    <a href="{{ path('app_phonenumber_new', {'contactId': contact.id}) }}">Add phone number</a>

    <hr>

    <h3>Email addresses</h3>
    <ul>
        {% for emailAddress in contact.emailAddresses %}
            <li>
                {{ emailAddress.type }} | {{ emailAddress.address }}
                |
                <form action="{{ path('app_emailaddress_delete', {'contactId': contact.id, 'emailAddressId': emailAddress.id}) }}"
                      method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    <input type="submit" value="Delete">
                </form>
                |
                <a href="{{ path('app_emailaddress_modify', {'contactId': contact.id, 'emailAddressId': emailAddress.id}) }}">modify</a>
            </li>
        {% else %}
            <p>No email addresses found :(</p>
        {% endfor %}
    </ul>

    <a href="{{ path('app_emailaddress_new', {'contactId': contact.id}) }}">Add email address</a>

{% endblock %}

address_book/src/AppBundle/Resources/views/Contact/showAll.html.twig
{% extends '::base.html.twig' %}

{% block body %}

    <p><a href="{{ path('app_contact_new') }}">Add new contact</a></p>

    <ul>
        {% for contact in contacts %}
            <li>
                <a href="{{ path('app_contact_show', {'id': contact.id}) }}">{{ contact.name }} {{ contact.surname }}</a>
                <form action="{{ path('app_contact_delete', {'id': contact.id}) }}" method="POST">
                    <input name="_method" type="hidden" value="DELETE">
                    <input type="submit" value="Delete">
                </form>
                <a href="{{ path('app_contact_modify', {'id': contact.id}) }}">Modify</a>
            </li>
        {% else %}
            <p>No contacts found</p>
        {% endfor %}
    </ul>

{% endblock %}